# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drink_cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=5)),
                ('ishot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='drinkmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_m', models.IntegerField(default=3)),
                ('price_l', models.IntegerField(default=3)),
                ('drinktype', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='food_cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isegg', models.BooleanField(default=True)),
                ('isvegetable', models.BooleanField(default=True)),
                ('issauce', models.BooleanField(default=True)),
                ('isdanishtoast', models.BooleanField(default=False)),
                ('issu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='foodmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=5)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_breakfast.food_cust')),
            ],
        ),
        migrations.AddField(
            model_name='drink_cust',
            name='drinktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_breakfast.drinkmenu'),
        ),
    ]
