# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw_breakfast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink_cust',
            name='drinktype',
        ),
        migrations.RemoveField(
            model_name='drink_cust',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drink_cust',
            name='size',
        ),
        migrations.AddField(
            model_name='drink_cust',
            name='isice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drink_cust',
            name='ismid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drinkmenu',
            name='drinktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_breakfast.drink_cust'),
        ),
        migrations.AlterField(
            model_name='drinkmenu',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
