# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_breakfast', '0002_auto_20180403_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenu',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
