# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_breakfast', '0003_auto_20180403_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkmenu',
            name='drinktype',
            field=models.IntegerField(default=3),
        ),
    ]
