# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_breakfast', '0004_auto_20180403_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='type',
            field=models.IntegerField(default=3),
        ),
    ]
