# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw_breakfast', '0005_auto_20180403_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw_breakfast.food_cust'),
        ),
    ]
