# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('draw_breakfast', '0007_auto_20180409_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('orderinfo', models.TextField(blank=True, null=True)),
                ('everyprice', models.IntegerField(default=5)),
                ('ordertime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
